### PR TITLE
Add ability to include extensions

### PR DESCRIPTION
**Pull request by ayan-b**

### CODE REVIEW

**Comment by ayan-b** [comment]
@chfw I am not really sure if we can use jinja2 extensions inside a `.haml` file.

**Comment by ayan-b** [comment]
I have made a release: https://pypi.org/project/moban-haml/ Will make a PR soon updating the README.

**Comment by chfw** [comment]
Yep, can you verify it. In theory, it looks like you have closed the extension door. Now you opened it.

**Comment by ayan-b** [comment]
> Yep, can you verify it. In theory, it looks like you have closed the extension door. Now you opened it.

Yup, one can use extension inside an `haml` file.

**Review by chfw — APPROVED** [review]
GTG

**Pull request merged**
